### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/python#2308]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [x] [Configure online editor](https://github.com/exercism/python/issues/2299)
- [x] [Add key features](https://github.com/exercism/python/issues/2300)
- [x] [Add tags](https://github.com/exercism/python/issues/2301)
- [x] [Add prerequisites to Practice Exercises](https://github.com/exercism/python/issues/2302)
- [x] [Update status of track](https://github.com/exercism/python/issues/2306)
- [x] [Update status of Concept Exercises](https://github.com/exercism/python/issues/2307) - _most current concept exercises are WIP, keeping issue open as status of these will change._
- [x] [Pass linting checks](https://github.com/exercism/python/issues/2303)
- [x] [Build Test Runner](https://github.com/exercism/python/issues/2304) - _test runner has bugs but is built.  Keeping issue open._
- [x] [Build Analyzer and Representer](https://github.com/exercism/python/issues/2305) (optional) - _analyzer and representer have both been built, both have bugs.  Keeping issues open._
- [x] [Add blurb to Concept Exercises](https://github.com/exercism/python/issues/2373)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7

**Comment by BethanyG** [comment]
Closing this.  Whatever is left on our "to do" list will be in separate issues.
